default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: record-collection
  username: test5
  password: test5
  host: localhost
  port: 5432

test:
  <<: *default
  database: record-collection
production:
  <<: *default
  url: <%= ENV['DBURI'] %>